### ISSUE TITLE
Error on a simpe query

### ISSUE THREAD

**Issue by kapish5467** [whoopnip/capiq-excel-downloader-py#4]
I am running the following code : 
import xlsxwriter
import xlsxwriter as xl
from capiq_excel import download_data

download_data(
    ['MSFT','AAPL'],  # Any id type. Ticker, name, CUSIP, ISIN, etc.
    financial_data_items=['IQ_REV', 'IQ_EBIT'], # Financial data variable names from Capital IQ
    freq='Q',
    num_periods=4
)
And getting the following error :

com_error                                 Traceback (most recent call last)
<ipython-input-16-bc056758908c> in <module>
      7 from capiq_excel import download_data
      8 
----> 9 download_data(
     10     ['MSFT','AAPL'],  # Any id type. Ticker, name, CUSIP, ISIN, etc.
     11     financial_data_items=['IQ_REV', 'IQ_EBIT'], # Financial data variable names from Capital IQ

c:\users\kapis\appdata\local\programs\python\python38-32\lib\site-packages\capiq_excel\main.py in download_data(company_ids, financial_data_items, market_data_items, ids_folder, data_folder, data_outpath, ids_outpath, restart, timeout, run_failed, **financial_command_kwargs)
     36 
     37     if restart or not os.path.exists(ids_outpath):
---> 38         capiq_ids = download_capiq_ids(
     39             company_ids,
     40             outpath=ids_outpath,

c:\users\kapis\appdata\local\programs\python\python38-32\lib\site-packages\capiq_excel\ids.py in download_capiq_ids(ids, outpath, folder)
     24 
     25     print('Populating XLSX files for ids')
---> 26     populate_all_ids_in_folder(folder)
     27 
     28     print('Combining all ids into a single CSV file')

c:\users\kapis\appdata\local\programs\python\python38-32\lib\site-packages\capiq_excel\ids.py in populate_all_ids_in_folder(folder, restart)
     37 
     38     for file in file_tracker.file_generator():
---> 39         populate_capiq_ids_for_file(file, excel)
     40 
     41 

c:\users\kapis\appdata\local\programs\python\python38-32\lib\site-packages\capiq_excel\workbook\populate\main.py in populate_capiq_ids_for_file(filepath, excel)
     75     wb = excel.Workbooks.Open(filepath)
     76     successful = _wait_for_capiq_result(excel)
---> 77     _copy_paste_values(excel, wb, cell_range='A:Z')
     78     excel.ActiveWorkbook.Close(SaveChanges=True)
     79     return successful

c:\users\kapis\appdata\local\programs\python\python38-32\lib\site-packages\capiq_excel\workbook\populate\main.py in _copy_paste_values(excel, wb, cell_range)
     83     ws = wb.Sheets('Sheet')
     84     ws.Range(cell_range).Copy()
---> 85     ws.Range(cell_range.split(':')[0]).PasteSpecial(Paste=constants.xlPasteValues, Operation=constants.xlNone)
     86     excel.CutCopyMode = False
     87 

~\AppData\Local\Temp\gen_py\3.8\00020813-0000-0000-C000-000000000046x0x1x9\_Worksheet.py in Range(self, Cell1, Cell2)
    237         # The method Range is actually a property, but must be used as a method to correctly pass the arguments
    238         def Range(self, Cell1=defaultNamedNotOptArg, Cell2=defaultNamedOptArg):
--> 239 		ret = self._oleobj_.InvokeTypes(197, LCID, 2, (9, 0), ((12, 1), (12, 17)),Cell1
    240 			, Cell2)
    241                 if ret is not None:

com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2146827284), None)

Can you tell me what am I missing here?

**Comment by julius-datajunkie** [comment]
Same issue here...

**Comment by VincentGaoHJ** [comment]
Same issue... Does anyone know how to fix it?

**Comment by nickderobertis** [comment]
Hey @VincentGaoHJ @zsljulius @kapish5467 I missed the earlier notifications about this. The error itself is quite a general one and is raised when the COM command does not work properly in Excel, which can be for a variety of reasons. I can see in the original traceback provided, it was having an issue while trying to paste values. Make sure that you are not trying to use Excel while the script runs and sometimes restarting Excel and the script is enough to make it work.

@VincentGaoHJ does the issue happen for you repeatedly, even after restarting Excel? If so, could you provide your traceback so I can see if it's the same issue? If you could also provide your version of Excel and OS that would be helpful.

**Comment by VincentGaoHJ** [comment]
Thanks for the prompt reply. Yes, this issue happens repeatedly.

Running code :

from capiq_excel import download_data
download_data(
    ['MSFT', 'AAPL'],  # Any id type. Ticker, name, CUSIP, ISIN, etc.
    financial_data_items=['IQ_TOTAL_REV', 'IQ_COST_REV'],  # Financial data variable names from Capital IQ
    market_data_items=['IQ_FLOAT_PERCENT'],  # Market data variable names from Capital IQ
    freq='Q',
    num_periods=6
)

Trackback:

Creating XLSX files with commands to get ids
Populating XLSX files for ids
Traceback (most recent call last):
  File "D:/OneDrive/Programming/documents_python/Entrepreneur/PoodleFiance/poodle-data/src/capitaliq/capiq.py", line 18, in <module>
    restart=False
  File "D:\Applications\Anaconda3\envs\poodlefinance\lib\site-packages\capiq_excel\main.py", line 41, in download_data
    folder=ids_folder
  File "D:\Applications\Anaconda3\envs\poodlefinance\lib\site-packages\capiq_excel\ids.py", line 26, in download_capiq_ids
    populate_all_ids_in_folder(folder)
  File "D:\Applications\Anaconda3\envs\poodlefinance\lib\site-packages\capiq_excel\ids.py", line 39, in populate_all_ids_in_folder
    populate_capiq_ids_for_file(file, excel)
  File "D:\Applications\Anaconda3\envs\poodlefinance\lib\site-packages\capiq_excel\workbook\populate\main.py", line 77, in populate_capiq_ids_for_file
    _copy_paste_values(excel, wb, cell_range='A:Z')
  File "D:\Applications\Anaconda3\envs\poodlefinance\lib\site-packages\capiq_excel\workbook\populate\main.py", line 85, in _copy_paste_values
    ws.Range(cell_range.split(':')[0]).PasteSpecial(Paste=constants.xlPasteValues, Operation=constants.xlNone)
  File "C:\Users\gaoha\AppData\Local\Temp\gen_py\3.7\00020813-0000-0000-C000-000000000046x0x1x9\_Worksheet.py", line 240, in Range
    , Cell2)
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2146827284), None)

Version:
Excel Version 2011
Windows 10 1909 (18363.900)

**Comment by nickderobertis** [comment]
Thanks @VincentGaoHJ for the additional information. I spun this project off from a larger project years ago, and I guess I never tested the `download_data` function as I already had Capital IQ ids so was using `download_data_for_capiq_ids`, and back then I wasn't yet regularly including tests in all my libraries. When I ran the `download_data` function now, I faced the same issue.

I believe the bug should be fixed now in `0.4.2`, so please upgrade and give it a try. I have also added a test so that I know it is all working. Let me know if you run into any further issues.

**Comment by VincentGaoHJ** [comment]
Thanks! The project is really helpful~
